version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3000:3000"
    environment:
      # Frontend environment variables
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NEXT_PUBLIC_WS_URL=ws://backend:8000
      - NEXT_PUBLIC_ENVIRONMENT=production
      - NEXT_PUBLIC_APP_VERSION=2.0.0-production
      - NEXT_PUBLIC_ENABLE_DEBUG=false
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - curagenie-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    ports:
      - "8000:8000"
    environment:
      # Backend environment variables
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DATABASE_PATH=curagenie_real.db
      - PORT=8000
      - DEBUG=false
      - ENVIRONMENT=production
      - SECRET_KEY=production-secret-key-change-me-in-real-deployment
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
      - CORS_ALLOW_CREDENTIALS=true
      - MAX_FILE_SIZE_MB=100
      - UPLOADS_DIR=uploads
      - ENABLE_REAL_GENOMIC_ANALYSIS=true
      - LOG_LEVEL=INFO
    volumes:
      - backend_uploads:/app/uploads
      - backend_db:/app/data
      - backend_logs:/app/logs
    networks:
      - curagenie-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

networks:
  curagenie-network:
    driver: bridge
    name: curagenie-network

volumes:
  backend_uploads:
    name: curagenie_uploads
  backend_db:
    name: curagenie_database
  backend_logs:
    name: curagenie_logs
